SELECT * INTO FINAL
FROM CSV_1_0_0
UNION ALL
SELECT * FROM CSV_1_1_0
UNION ALL
SELECT * FROM CSV_1_2_0
UNION ALL
SELECT * FROM CSV_1_3_0
UNION ALL
SELECT * FROM CSV_1_4_0
UNION ALL
SELECT * FROM CSV_1_5_0
UNION ALL
SELECT * FROM CSV_1_10_0
UNION ALL
SELECT * FROM CSV_1_11_0
UNION ALL
SELECT * FROM CSV_1_12_0
UNION ALL
SELECT * FROM CSV_1_13_0
UNION ALL
SELECT * FROM CSV_1_14_0
UNION ALL
SELECT * FROM CSV_1_15_0

--DROP TABLE FINAL


